# =============================================================================
# DockAnalyzer — Interaction scoring
# Section 1 — Header, imports, aliases and public interface
# =============================================================================

"""
Interaction scoring, aggregation, normalization and ranking for DockAnalyzer.

This module converts molecular-interaction results generated by DockAnalyzer
into transparent and reproducible numerical scores.

Supported interaction families include:

- general atomic contacts;
- hydrogen bonds;
- hydrophobic interactions;
- pi-related interactions;
- salt bridges;
- steric clashes;
- externally defined or custom interaction types.

The module is responsible for:

1. assigning configurable weights to individual interactions;
2. incorporating interaction strength and geometric quality;
3. applying penalties, including steric-clash penalties;
4. preventing accidental double counting;
5. aggregating scores by interaction, residue and docking pose;
6. normalizing scores when requested;
7. ranking multiple docking poses;
8. generating interpretable score decompositions;
9. integrating scoring results with ``DockModel``;
10. producing serialization-safe scoring structures.

The score generated by this module is a DockAnalyzer interaction score. It is
a configurable heuristic used to compare the quality and diversity of detected
interactions. It must not be interpreted as a binding free energy, docking
affinity or thermodynamic quantity expressed in kcal/mol.

Design principles
-----------------
The scoring layer does not redetect molecular interactions and does not replace
the geometric or chemical validation performed by the specialized modules:

- :mod:`contacts`;
- :mod:`hbonds`;
- :mod:`hydrophobic`;
- :mod:`pi`;
- :mod:`saltbridge`.

Instead, it consumes their result objects, mappings or serialized
representations and converts them into standardized score components.

The implementation is designed to operate:

1. inside UCSF ChimeraX, using native molecular objects;
2. outside ChimeraX, using ordinary Python objects;
3. with synthetic objects used by the DockAnalyzer self-tests;
4. with dictionary-based data loaded from JSON or tabular exports.

Specialized interaction modules are intentionally not imported globally here.
Avoiding those imports reduces circular dependencies and allows ``scoring.py``
to work with structurally compatible third-party objects. Imports that are
strictly required for specialized adapters should be performed locally in the
corresponding functions.

Notes
-----
Positive score components represent favorable interactions.

Negative score components represent penalties, such as steric clashes or
invalid geometries.

A score of zero represents a neutral, ignored or rejected contribution,
depending on the associated metadata.

Raw and normalized scores must remain separate. Normalization must never
silently overwrite the original raw score.
"""

from __future__ import annotations


# -----------------------------------------------------------------------------
# 1.1. Standard-library imports
# -----------------------------------------------------------------------------

from collections import Counter, defaultdict
from dataclasses import (
    asdict,
    dataclass,
    field,
    fields,
    is_dataclass,
    replace,
)
from enum import Enum
from functools import lru_cache
from math import isfinite
from statistics import fmean, median
from types import MappingProxyType
from typing import (
    Any,
    Callable,
    ClassVar,
    Collection,
    DefaultDict,
    Dict,
    Final,
    FrozenSet,
    Hashable,
    Iterable,
    Iterator,
    List,
    Literal,
    Mapping,
    MutableMapping,
    NamedTuple,
    Optional,
    Protocol,
    Sequence,
    Set,
    Tuple,
    TypeAlias,
    TypeVar,
    Union,
    runtime_checkable,
)

import contextlib
import json
import math
import warnings


# -----------------------------------------------------------------------------
# 1.2. NumPy imports
# -----------------------------------------------------------------------------

import numpy as np
from numpy.typing import NDArray


# -----------------------------------------------------------------------------
# 1.3. Internal DockAnalyzer imports
# -----------------------------------------------------------------------------
#
# The two import modes allow this module to work:
#
# - as part of an installed/imported DockAnalyzer package; and
# - as a directly executed file located beside the other project modules.
#
# Specialized interaction modules are not imported globally. Their result
# objects will be recognized through common attributes, mappings, protocols
# and, when strictly necessary, local imports.
# -----------------------------------------------------------------------------

try:
    from . import config
    from .utils import (
        DockLogger,
        DockModel,
    )
except ImportError:
    import config
    from utils import (
        DockLogger,
        DockModel,
    )


# -----------------------------------------------------------------------------
# 1.4. Module metadata
# -----------------------------------------------------------------------------

__author__: Final[str] = "Leonardo Bastos and DockAnalyzer contributors"
__version__: Final[str] = "0.1.0"
__license__: Final[str] = "MIT"

_MODULE_NAME: Final[str] = "scoring"
_MODULE_DESCRIPTION: Final[str] = (
    "Interaction scoring, aggregation, normalization and multipose ranking "
    "for DockAnalyzer."
)

_LOGGER: Final[DockLogger] = DockLogger(
    _MODULE_NAME,
)


# -----------------------------------------------------------------------------
# 1.5. Public interface
# -----------------------------------------------------------------------------
#
# Public names are registered incrementally at the end of each section. This
# prevents functions and implementation details that begin with an underscore
# from being unintentionally exported.
# -----------------------------------------------------------------------------

__all__: List[str] = []


# -----------------------------------------------------------------------------
# 1.6. Generic type variables
# -----------------------------------------------------------------------------

T = TypeVar("T")
K = TypeVar("K", bound=Hashable)
V = TypeVar("V")

InteractionT = TypeVar("InteractionT")
ComponentT = TypeVar("ComponentT")
ResidueT = TypeVar("ResidueT")
PoseT = TypeVar("PoseT")
ModelT = TypeVar("ModelT")


# -----------------------------------------------------------------------------
# 1.7. Numeric aliases
# -----------------------------------------------------------------------------

Number: TypeAlias = Union[
    int,
    float,
    np.integer,
    np.floating,
]

ScoreValue: TypeAlias = np.float64
WeightValue: TypeAlias = np.float64
MultiplierValue: TypeAlias = np.float64
PenaltyValue: TypeAlias = np.float64

FloatArray: TypeAlias = NDArray[np.float64]
IntegerArray: TypeAlias = NDArray[np.int64]
BooleanArray: TypeAlias = NDArray[np.bool_]


# -----------------------------------------------------------------------------
# 1.8. Generic interaction and model aliases
# -----------------------------------------------------------------------------
#
# ``Any`` is intentional for the molecular-object aliases. ChimeraX objects,
# DockAnalyzer dataclasses, mappings and test doubles do not share a common
# nominal base class.
# -----------------------------------------------------------------------------

InteractionLike: TypeAlias = Any
InteractionResultLike: TypeAlias = Any
InteractionCollection: TypeAlias = Iterable[InteractionLike]
InteractionSequence: TypeAlias = Sequence[InteractionLike]

ScoreComponentLike: TypeAlias = Any
ScoreComponentCollection: TypeAlias = Sequence[ScoreComponentLike]

ResidueLike: TypeAlias = Any
AtomLike: TypeAlias = Any
PoseLike: TypeAlias = Any
ModelLike: TypeAlias = Any
DockModelLike: TypeAlias = Any


# -----------------------------------------------------------------------------
# 1.9. Identifier aliases
# -----------------------------------------------------------------------------

InteractionIdentifier: TypeAlias = str
InteractionSource: TypeAlias = str
InteractionTypeName: TypeAlias = str
InteractionSubtypeName: TypeAlias = str

AtomIdentifier: TypeAlias = str
ResidueIdentifier: TypeAlias = str
PoseIdentifier: TypeAlias = str
ModelIdentifier: TypeAlias = str

ResidueKey: TypeAlias = Tuple[
    str,
    Optional[int],
    Optional[str],
]

AtomPairKey: TypeAlias = Tuple[
    AtomIdentifier,
    AtomIdentifier,
]

ResiduePairKey: TypeAlias = Tuple[
    ResidueKey,
    ResidueKey,
]

InteractionKey: TypeAlias = Tuple[
    str,
    ...,
]


# -----------------------------------------------------------------------------
# 1.10. Mapping, metadata and statistics aliases
# -----------------------------------------------------------------------------

Metadata: TypeAlias = Mapping[str, Any]
MutableMetadata: TypeAlias = MutableMapping[str, Any]

Statistics: TypeAlias = Dict[str, Any]
Summary: TypeAlias = Dict[str, Any]

ScoreMapping: TypeAlias = Mapping[str, Number]
MutableScoreMapping: TypeAlias = MutableMapping[str, Number]

WeightMapping: TypeAlias = Mapping[str, Number]
MutableWeightMapping: TypeAlias = MutableMapping[str, Number]

MultiplierMapping: TypeAlias = Mapping[str, Number]
PenaltyMapping: TypeAlias = Mapping[str, Number]

InteractionMapping: TypeAlias = Mapping[str, Any]
MutableInteractionMapping: TypeAlias = MutableMapping[str, Any]


# -----------------------------------------------------------------------------
# 1.11. JSON-compatible aliases
# -----------------------------------------------------------------------------

JSONPrimitive: TypeAlias = Union[
    str,
    int,
    float,
    bool,
    None,
]

JSONValue: TypeAlias = Union[
    JSONPrimitive,
    List["JSONValue"],
    Dict[str, "JSONValue"],
]

JSONMapping: TypeAlias = Dict[str, JSONValue]


# -----------------------------------------------------------------------------
# 1.12. Scoring strategy aliases
# -----------------------------------------------------------------------------

NormalizationMode: TypeAlias = Literal[
    "none",
    "interaction_count",
    "residue_count",
    "ligand_heavy_atoms",
    "contact_count",
    "maximum_absolute",
    "min_max",
    "z_score",
]

AggregationMode: TypeAlias = Literal[
    "sum",
    "mean",
    "maximum",
    "minimum",
    "weighted_mean",
]

DeduplicationMode: TypeAlias = Literal[
    "none",
    "exact",
    "atom_pair",
    "residue_pair",
    "interaction_group",
]

ScoreDirection: TypeAlias = Literal[
    "higher_is_better",
    "lower_is_better",
]

InteractionPolarity: TypeAlias = Literal[
    "favorable",
    "penalty",
    "neutral",
    "unknown",
]

InteractionStrength: TypeAlias = Literal[
    "strong",
    "moderate",
    "weak",
    "unclassified",
    "unknown",
]

GeometryQuality: TypeAlias = Literal[
    "optimal",
    "favorable",
    "weak",
    "borderline",
    "rejected",
    "unclassified",
    "unknown",
]


# -----------------------------------------------------------------------------
# 1.13. Callable aliases
# -----------------------------------------------------------------------------

InteractionPredicate: TypeAlias = Callable[
    [InteractionLike],
    bool,
]

InteractionKeyFunction: TypeAlias = Callable[
    [InteractionLike],
    Hashable,
]

InteractionTypeResolver: TypeAlias = Callable[
    [InteractionLike],
    InteractionTypeName,
]

InteractionScoreFunction: TypeAlias = Callable[
    [InteractionLike],
    ScoreComponentLike,
]

ScoreReducer: TypeAlias = Callable[
    [Iterable[Number]],
    Number,
]

MetadataFactory: TypeAlias = Callable[
    [],
    MutableMetadata,
]


# -----------------------------------------------------------------------------
# 1.14. Structural protocols
# -----------------------------------------------------------------------------

@runtime_checkable
class InteractionTypeProvider(Protocol):
    """
    Protocol for objects that expose an interaction type.

    Implementations may use a property, dataclass field or ordinary attribute.
    Objects do not need to explicitly inherit from this protocol.
    """

    @property
    def interaction_type(self) -> Any:
        """Return the interaction type or category."""


@runtime_checkable
class InteractionScoreProvider(Protocol):
    """
    Protocol for objects exposing a previously calculated score.

    A specialized module may expose a local geometric score. The global
    DockAnalyzer scorer may use that value as an input but should not assume
    that it is already on the same scale as the final interaction score.
    """

    @property
    def score(self) -> Any:
        """Return a local or previously calculated score."""


@runtime_checkable
class InteractionStrengthProvider(Protocol):
    """Protocol for objects exposing an interaction-strength classification."""

    @property
    def strength(self) -> Any:
        """Return the strength label."""


@runtime_checkable
class InteractionClassificationProvider(Protocol):
    """Protocol for objects exposing a geometric or chemical classification."""

    @property
    def classification(self) -> Any:
        """Return the interaction classification."""


@runtime_checkable
class InteractionMetadataProvider(Protocol):
    """Protocol for objects exposing metadata."""

    @property
    def metadata(self) -> Any:
        """Return interaction metadata."""


@runtime_checkable
class ResidueScoreProvider(Protocol):
    """Protocol for objects associated with a receptor or ligand residue."""

    @property
    def residue(self) -> Any:
        """Return the associated residue-like object."""


@runtime_checkable
class PoseIdentifierProvider(Protocol):
    """Protocol for objects exposing a docking-pose identifier."""

    @property
    def pose_id(self) -> Any:
        """Return the pose identifier."""


# -----------------------------------------------------------------------------
# 1.15. Empty immutable objects
# -----------------------------------------------------------------------------

_EMPTY_METADATA: Final[Mapping[str, Any]] = MappingProxyType({})
_EMPTY_SCORE_MAPPING: Final[Mapping[str, Number]] = MappingProxyType({})
_EMPTY_INTERACTION_TUPLE: Final[Tuple[InteractionLike, ...]] = ()
_EMPTY_COMPONENT_TUPLE: Final[Tuple[ScoreComponentLike, ...]] = ()
_EMPTY_RESIDUE_KEY_TUPLE: Final[Tuple[ResidueKey, ...]] = ()
_EMPTY_STRING_TUPLE: Final[Tuple[str, ...]] = ()


# -----------------------------------------------------------------------------
# 1.16. Initial public names
# -----------------------------------------------------------------------------

_SECTION_1_PUBLIC_NAMES: Final[Tuple[str, ...]] = (
    # Numeric aliases
    "Number",
    "ScoreValue",
    "WeightValue",
    "MultiplierValue",
    "PenaltyValue",
    "FloatArray",
    "IntegerArray",
    "BooleanArray",

    # Generic object aliases
    "InteractionLike",
    "InteractionResultLike",
    "InteractionCollection",
    "InteractionSequence",
    "ScoreComponentLike",
    "ScoreComponentCollection",
    "ResidueLike",
    "AtomLike",
    "PoseLike",
    "ModelLike",
    "DockModelLike",

    # Identifiers and keys
    "InteractionIdentifier",
    "InteractionSource",
    "InteractionTypeName",
    "InteractionSubtypeName",
    "AtomIdentifier",
    "ResidueIdentifier",
    "PoseIdentifier",
    "ModelIdentifier",
    "ResidueKey",
    "AtomPairKey",
    "ResiduePairKey",
    "InteractionKey",

    # Mappings and metadata
    "Metadata",
    "MutableMetadata",
    "Statistics",
    "Summary",
    "ScoreMapping",
    "MutableScoreMapping",
    "WeightMapping",
    "MutableWeightMapping",
    "MultiplierMapping",
    "PenaltyMapping",
    "InteractionMapping",
    "MutableInteractionMapping",

    # JSON aliases
    "JSONPrimitive",
    "JSONValue",
    "JSONMapping",

    # Strategy aliases
    "NormalizationMode",
    "AggregationMode",
    "DeduplicationMode",
    "ScoreDirection",
    "InteractionPolarity",
    "InteractionStrength",
    "GeometryQuality",

    # Callable aliases
    "InteractionPredicate",
    "InteractionKeyFunction",
    "InteractionTypeResolver",
    "InteractionScoreFunction",
    "ScoreReducer",
    "MetadataFactory",

    # Structural protocols
    "InteractionTypeProvider",
    "InteractionScoreProvider",
    "InteractionStrengthProvider",
    "InteractionClassificationProvider",
    "InteractionMetadataProvider",
    "ResidueScoreProvider",
    "PoseIdentifierProvider",
)

for public_name in _SECTION_1_PUBLIC_NAMES:
    if public_name not in __all__:
        __all__.append(public_name)


# =============================================================================
# End of Section 1
# =============================================================================




