#!/bin/bash

# Directory containing the .pdbqt files to be split.
# Example: /mnt/c/Users/User/Desktop/Docking_poses
INPUT="/path/to/pdbqt/files"

# Output directory 
OUTPUT="$INPUT/poses"
mkdir -p "$OUTPUT"

# Loop in .pdbqt files
for file in "$INPUT"/*.pdbqt; do

    # Verify the existence of .pdbqt files - Skip if no matching file exists
    [ -e "$file" ] || continue

    # Create an output directory for each ligand
    base=$(basename "$file" .pdbqt)
    
    mkdir -p "$OUTPUT/$base"

    echo "===================================="
    echo "Converting: $base"

    # Convert all poses into individual PDB files
    obabel "$file" -O "$OUTPUT/$base/pose.pdb" -m

    # Rename poses according to affinity ranking  
    contador=1
    for pose in "$OUTPUT/$base"/pose*.pdb; do
        mv "$pose" "$OUTPUT/$base/pose${contador}.pdb"
        ((contador++))
    done

    echo "✓ $((contador-1)) poses salvas em $OUTPUT/$base"

done

echo "===================================="
echo "Done!"
